name: deploy

on:
  push:
    branches: [ develop ]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin' # https://github.com/actions/setup-java

      ## create application-secret.yml
      - name: make application-secret.yml
        #if: contains(github.ref, 'develop')
        run: |
          cd ./src/main/resources
          touch ./application-secret.yml
          echo "${{ secrets.SECRET_YML }}" > ./application-secret.yml
        shell: bash

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean build -x test
        shell: bash
        
      - name: Test with Gradle
        run: SPRING_PROFILES_ACTIVE=[test] ./gradlew test
        
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_SSH_ID }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            whoami
            cd /home/ubuntu/jasome-server
            echo "${{ secrets.SECRET_YML }}" > ./src/main/resources/application-secret.yml
            ./scripts/build.sh
            ./scripts/stop.sh
            ./scripts/start.sh
