name: test

on:
  push:
    branches: [ feature/*, bugfix, hotfix ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin' # https://github.com/actions/setup-java

      ## create application-secret.yml
      - name: make application-secret.yml
        #if: contains(github.ref, 'develop')
        run: |
          cd ./src/main/resources
          touch ./application-secret.yml
          echo "${{ secrets.SECRET_YML }}" > ./application-secret.yml
        shell: bash

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean build -x test
        shell: bash
        
      - name: Test with Gradle
        run: ./gradlew --info test
